### PR TITLE
Add ride map

### PR DESCRIPTION
**Pull request by raisinrand**
### Summary 

Adds a Google map with markers on placeholder locations on the ride request page.

### Test Plan 
Tested manually on Android emulator

Screenshot_1606174142

### Notes 

Requires new environment variables for api keys, so everyone will need a new .env file for the app when this is merged. If you are going to test this let me know and I will send the .env file.

Api key access not tested on iOS

### CODE REVIEW

**Review by tyang98 — COMMENTED** [review]
The map appears properly on Android. The next step is to figure out how to select locations without hardcoded markers.

**Review by tyang98 — APPROVED** [review]
The map appears properly on Android. The next step is to figure out how to select locations without hardcoded markers.

**Comment by mg2239** [comment]
> The map appears properly on Android (we will need to test on iOS once the bugs get fixed). The next step is to figure out how to select locations without hardcoded markers.

what bugs are occuring on iOS?

**Comment by tyang98** [comment]
> > The map appears properly on Android (we will need to test on iOS once the bugs get fixed). The next step is to figure out how to select locations without hardcoded markers.
> 
> what bugs are occuring on iOS?

There are no bugs related to the map on iOS, but we aren't able to run iOS rn because of errors

**Comment by mg2239** [comment]
ah yeah forgot about that

**Pull request closed without merging**
